package tr.edu.fsm.dersprog.FSMVUDersProg;

// Generated 30.Tem.2015 15:30:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users", catalog = "sql285436")
public class Users implements java.io.Serializable {

	private Integer idUsers;
	private String uname;
	private String password;

	public Users() {
	}

	public Users(String uname, String password) {
		this.uname = uname;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUsers", unique = true, nullable = false)
	public Integer getIdUsers() {
		return this.idUsers;
	}

	public void setIdUsers(Integer idUsers) {
		this.idUsers = idUsers;
	}

	@Column(name = "uname", length = 45)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
