package tr.edu.fsm.dersprog.FSMVUDersProg.Derslik;
// Generated 05.AIu.2015 11:12:41 by Hibernate Tools 4.3.1

/**
 * Derslik generated by hbm2java
 */
public class Derslik implements java.io.Serializable {

	private Integer id;
	private int derslikKodu;
	private String derslikAdi;
	private int sorumluBolumId;

	public Derslik() {
	}

	public Derslik(int derslikKodu, String derslikAdi, int sorumluBolumId) {
       this.derslikKodu = derslikKodu;
       this.derslikAdi = derslikAdi;
       this.sorumluBolumId = sorumluBolumId;
    }

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getDerslikKodu() {
		return this.derslikKodu;
	}

	public void setDerslikKodu(int derslikKodu) {
		this.derslikKodu = derslikKodu;
	}

	public String getDerslikAdi() {
		return this.derslikAdi;
	}

	public void setDerslikAdi(String derslikAdi) {
		this.derslikAdi = derslikAdi;
	}

	public int getSorumluBolumId() {
        return this.sorumluBolumId;
    }

	public void setSorumluBolumId(int sorumluBolumId) {
        this.sorumluBolumId = sorumluBolumId;
    }




}
